# Generated by Django 2.1 on 2020-03-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('courseId', models.IntegerField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('studentId', models.IntegerField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=32)),
                ('courseId', models.ManyToManyField(to='App.CourseModel')),
            ],
        ),
    ]
